apiVersion: v1
kind: Secret
metadata:
  name: juro-dora-test-apm
  namespace: juro-dora-test
  labels:
    app: juro-dora-test
type: Opaque
stringData:
  SW_APM_SERVICE_KEY: "<swo-injestion-token>:juro-dora-test"
